services:
  web:
    image: nginx:1.26.0
    volumes:
      - ./app/web:/usr/share/nginx/html
    ports:
      - "8080:80"

  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parksmart
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    build: ./app
    volumes:
      - ./app:/app
    command: python /app/python/start.py
    depends_on:
      - db
    links:
      - db
      - mosquitto
    ports:
      - "2000:2000"

networks:
  custom_network:
    driver: bridge
