services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto:/mosquitto/config:rw
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./nginx:/usr/share/nginx/html
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ParkSmart
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped
