services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto:/mosquitto/config:rw
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ParkSmart
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - ./backend:/var/www/html
    restart: unless-stopped

  php:
    build: ./php
    container_name: php
    volumes:
      - ./php:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    restart: unless-stopped
